# Generated by Django 5.2.3 on 2025-11-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Departapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
